"""
manga curta simples (MCS) = 1.80
manga longa simples (MLS) = 2.10
Manga curta com estampa (MCE)= 2.90
Manga Longa Com Estampa (MLE)= 3.20

Se número de camisetas for menor que 20 não há desconto na venda; 
Se número de camisetas for igual ou maior que 20 e menor que 200, o desconto será de 5%; 
Se número de camisetas for igual ou maior que 200 e menor que 2000, o desconto será de 7%; 
Se número de camisetas for igual ou maior que 2000 e menor ou igual que 20000, o desconto será de 12%; 
Se número de camisetas for maior que 20000, não é aceito pedidos nessa quantidade de camisetas;  

Para o adicional de frete por transportadora (1) é cobrado um valor extra de 100 reais; 
Para o adicional de frete por Sedex (2) é cobrado um valor extra de 200 reais; 
Para o adicional de retirar o pedido na fábrica (0) é cobrado um valor extra de 0 reais; 
"""
